# Generated by Django 5.2.11 on 2026-02-26 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalistSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journalist', models.ForeignKey(limit_choices_to={'role': 'journalist'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscribed_by_readers', to=settings.AUTH_USER_MODEL)),
                ('reader', models.ForeignKey(limit_choices_to={'role': 'reader'}, on_delete=django.db.models.deletion.CASCADE, related_name='journalist_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reader', 'journalist')},
            },
        ),
    ]
