# Generated by Django 5.2.11 on 2026-02-26 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_journalistsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalistsubscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='journalistsubscription',
            name='active',
        ),
        migrations.AlterField(
            model_name='journalistsubscription',
            name='journalist',
            field=models.ForeignKey(limit_choices_to={'role': 'journalist'}, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
