# Generated by Django 5.2.11 on 2026-02-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_journalistsubscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalistsubscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
