# Generated by Django 5.2.11 on 2026-03-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_articlesubscription_delete_journalistsubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_approved',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='is_approved',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='newsletters', to='news.article'),
        ),
    ]
