# Generated by Django 5.2.11 on 2026-03-06 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='journalist_subscriptions',
            field=models.ManyToManyField(blank=True, help_text='Journalists that this reader is subscribed to.', limit_choices_to={'role': 'journalist'}, related_name='journalist_subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
