# Generated by Django 5.2.11 on 2026-02-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_subscribed_publishers'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscribed_publishers',
        ),
        migrations.AddField(
            model_name='customuser',
            name='reader_subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribed_readers', to='news.publisher'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('journalist', 'Journalist'), ('editor', 'Editor')], max_length=20),
        ),
    ]
