# Generated by Django 5.2.11 on 2026-02-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_subscribed_publishers_and_more'),
        ('news', '0002_alter_article_options_alter_newsletter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reader_subscriptions',
            field=models.ManyToManyField(blank=True, help_text='Publishers that this reader is subscribed to.', related_name='subscribed_readers', to='news.publisher'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('journalist', 'Journalist'), ('editor', 'Editor')], help_text='Role of the user: reader, journalist, or editor.', max_length=20),
        ),
    ]
